# Generated by Django 5.0.6 on 2025-07-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_user_credits_user_plan_user_plan_expiry_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='remaining_credits',
            field=models.IntegerField(default=0),
        ),
    ]
