# Generated by Django 5.0.6 on 2025-07-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_subscription_remaining_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_expiry',
        ),
    ]
