# Generated by Django 5.0.6 on 2025-07-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='credits',
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='remaining_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
