# Generated by Django 5.0.6 on 2025-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='credits_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
