# Generated by Django 5.0.6 on 2025-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_subscription_credits_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='credits_purchased',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('credit_purchase', 'Credit Purchase')], default='subscription', max_length=20),
        ),
    ]
