# Generated by Django 5.0.6 on 2025-07-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_payment_billing_cycle_payment_credits_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='had_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
