# Generated by Django 5.0.6 on 2025-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_subscription_had_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='credits_used',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
