# Generated by Django 5.0.6 on 2025-07-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_userupload_credits_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='credits_used',
        ),
    ]
